project_name: kata
release:
  github:
    owner: Tim-0731-Hzt
    name: kubectl-kata
builds:
  - id: kata
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/Tim-0731-Hzt/kubectl-kata/pkg/version.version=
archives:
  - id: kata
    builds:
    - kata
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
