apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kata
spec:
  version: "v0.1.0"
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/Tim-0731-Hzt/kubectl-kata/releases/download/v0.1.0/kata_linux_amd64.tar.gz
      sha256: c5264fd12b8d25b26590ebd2a5c425db33dd43d2
      files:
        - from: "./kata"
          to: "."
        - from: LICENSE
          to: "."
      bin: "kata"
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/Tim-0731-Hzt/kubectl-kata/releases/download/v0.1.0/kata_darwin_amd64.tar.gz
      sha256: c5264fd12b8d25b26590ebd2a5c425db33dd43d2
      files:
        - from: "./kata"
          to: "."
        - from: LICENSE
          to: "."
      bin: "kata"
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/Tim-0731-Hzt/kubectl-kata/releases/download/v0.1.0/kata_windows_amd64.zip
      sha256: c5264fd12b8d25b26590ebd2a5c425db33dd43d2
      files:
        - from: "/kata.exe"
          to: "."
        - from: LICENSE
          to: "."
      bin: "kata.exe"
  shortDescription: A new plugin
  homepage: https://github.com/Tim-0731-Hzt/kubectl-kata
  caveats: |
    Usage:
      $ kubectl kata

    For additional options:
      $ kubectl kata --help
      or https://github.com/Tim-0731-Hzt/kubectl-kata/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
